# Generated by Django 5.2.4 on 2025-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.IntegerField()),
            ],
        ),
    ]
