# Generated by Django 5.2.4 on 2025-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJANGO_USERS',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('u_mob', models.CharField(max_length=10)),
                ('reg_on', models.DateTimeField()),
            ],
        ),
    ]
