# Generated by Django 5.2.4 on 2025-07-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hash_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='django_users',
            name='reg_on',
        ),
    ]
