# Generated by Django 5.2.4 on 2025-07-31 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_app', '0003_django_users_reg_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django_users',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='django_users',
            name='reg_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 31, 22, 55, 48, 393326)),
        ),
    ]
