# Generated by Django 5.2.4 on 2025-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('std_id', models.IntegerField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(default='std_x', max_length=50)),
                ('std_course', models.CharField(max_length=50)),
                ('std_age', models.IntegerField()),
            ],
        ),
    ]
