# Generated by Django 5.2.4 on 2025-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(default='emp_x', max_length=100)),
                ('emp_mob', models.CharField(max_length=10, unique=True)),
                ('emp_mail', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
